### ISSUE TITLE
Cannot see chat messages

### ISSUE THREAD

**Issue by badonyx** [BlowaterNostr/blowater#235]
I can see who I have DMed with but I cannot see any messages.

**Comment by BlowaterNostr** [comment]
@badonyx Can you have a screenshot?

**Comment by badonyx** [comment]
<img width="520" alt="Screenshot 2023-10-17" src="https://github.com/BlowaterNostr/blowater/assets/110633279/9232e96b-b444-487d-afb8-31f7f0cd2e10">

I have enabled all the relevant permissions for Alby so not sure why I get "User rejected Alby login".

**Comment by BlowaterNostr** [comment]
@badonyx thanks, we will take a look

**Comment by BlowaterNostr** [comment]
@badonyx The 2nd error should be fixed. We will look at the 1st error.

**Comment by BlowaterNostr** [comment]
@shaibearary Can you take a look at this bug as well?

**Comment by 0xtrr** [comment]
I'm experiencing the same problem as OP (1st error)

**Comment by BlowaterNostr** [comment]
- @badonyx @0xtrr fixed in #242 
The root cause is that Alby had a breaking change in their API so that we had to change accordingly.

Be aware that using Alby is 3-10X slower on loading if you have thousands of kind4s.

Other than that, things should be fine. I rarely use NIP-07 extensions with Blowater because most extensions' encryption/decription are not optimized. We plan to release our own kind4 optimized NIP-07 extension in the future.

**Comment by BlowaterNostr** [comment]
@0xtrr I can zap you if you give me your npub

**Comment by badonyx** [comment]
You can find me here.

https://nostorg.github.io/.well-known/nostr.json
