### ISSUE TITLE
New UI/UX proposal

### ISSUE THREAD

**Issue by dtonon** [BlowaterNostr/blowater#343]
@BlowaterNostr here is an initial design proposal about the review you asked me.

The idea is to emphasize the columns structure, eliminating any top/bottom elements so they can flow freely.

The first narrow column on the left contains the menu for all the main areas:

- New Message
- Chat lists
- Inbox (current strangers)
- Settings
- Profile

I would always show the current user on the right; this area can have some basic useful information and actions; it makes it really easy to identify who you are chatting with; and it allows you to remove the name at the top of the main chat column.

When the user hovers a message, a "More Information" link appears. By clicking it, the details (id, relay, json, etc.) are shown on the right column, temporarily hiding the user's profile.

![image](https://github.com/BlowaterNostr/blowater/assets/89577423/8353f9f4-d44d-4aaf-abe5-495d8727469c)

If you like this ideas I can go on sketching some the details, like the new message UI, the notifications, etc.

**Comment by BlowaterNostr** [comment]
@dtonon 
"I would always show the current user on the right;"
The problem here is that the right panel is not only used to show to current user. If I share a npub to you, you can see a card and you can click the card to see the detail.
<img width="1086" alt="image" src="https://github.com/BlowaterNostr/blowater/assets/127284497/51b72651-a0f1-42ef-aafb-e5718de72b18">

**Comment by BlowaterNostr** [comment]
@dtonon Yes, we can continue with this design. In terms of implementation order, which part do you suggest me to implement first?

My development style is continous shipping. So I won't implement everything in a big PR and ship. Will break them down.

This might introduce more design work to you because you needs to design with modularity in mind. If you have considered it already, brilliant.

**Comment by dtonon** [comment]
@BlowaterNostr it is not easy, and often effective, to use a phased approach in a redesign; half-ways are difficult to produce and a little dangerous because users have to adapt multiple times to a different UI/UX. The best approach would be a monolithic release. If it is not possible, we can split the work into the structural part and the details:

A) Revise the left menu column following the new structure, move the "inbox" (strangers), and keep the right column always open;

B) Focus on all the UI design details of the main section;

C) Review the UI of the Profile and Preference sections;

All these steps should take into consideration both the desktop and the smartphone views.

**Comment by BlowaterNostr** [comment]
@dtonon 
The question comes down to if your design will change the interaction semantics of the software.

If it's a pure visual change, then I can do a monolithic release easily. If the interfaction changes, need to be modular.

Maybe we can separate the visual redesign and interfaction redesign.

**Comment by BlowaterNostr** [comment]
@dtonon Can I get the logo vectors for the new side bar first?

**Comment by dtonon** [comment]
@BlowaterNostr in the figma project you can find the basic structure for the mobile version:

<img width="1063" alt="Screenshot 2024-01-24 alle 18 26 24" src="https://github.com/BlowaterNostr/blowater/assets/89577423/12b93906-be33-4ec6-a51a-a9b7bbd2fac2">
<br/><br/>

I replaced (also in the desktop design) the "Send" icon with a lens, it seems more logic because when you click it a search interface is displayed. Instead the original icon is now used to trigger the actual message send.
